version: "3"

services:
  psmysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}

  prestashop_1.7.6.9:
    image: prestashop/prestashop:1.7.6.9-7.2-apache
    depends_on:
      - psmysql
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/modules/${PS_MODULE_NAME}
    environment:
      - DB_SERVER=psmysql
      - DB_PREFIX=ps1769_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8081
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 9001:80
      env_file: .env