name: PHP tests
on: [push]
jobs:
  php-linter:
    name: PHP Syntax check 7.1|7.2|7.3|7.4|8.0|8.1|8.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: PHP syntax checker 7.1
        uses: prestashop/github-action-php-lint/7.1@master
      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master
      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['1.7.0.3', '1.7.2.4', '1.7.5.0', '1.7.8.1', 'latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Cache vendor folder
        uses: actions/cache@v1
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install

      - name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:${{ matrix.presta-versions }}

      - name : Run PHPStan
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module phpstan/phpstan:0.12 analyse --configuration=/web/module/tests/phpstan/phpstan.neon --error-format github

      - name : Run PHPunit tests
        run: make phpunit
  phpunit:
      name: PHPUnit
      runs-on: ubuntu-latest
      strategy:
        matrix:
          presta-versions: ['1.7.0.3', '1.7.2.4', '1.7.5.0', '1.7.8.1', 'latest']
      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: xdebug

        - name: Checkout
          uses: actions/checkout@v3

        - name: Cache vendor folder
          uses: actions/cache@v3 
          with:
            path: vendor
            key: php-${{ hashFiles('composer.lock') }}

        - name: Cache composer folder
          uses: actions/cache@v1
          with:
            path: ~/.composer/cache
            key: php-composer-cache

        - run: composer install
        - run: make phpunit
