name: Playwright Tests
on:
  push:
    branches: [ main, master, refactor/feed ]
  pull_request:
    branches: [ main, master, refactor/feed ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Docker compose environment
      run: docker-compose --env-file .env.ci up -d

    - name: Wait for server to be ready
      run: |
        echo "Waiting for server to be ready..."
        timeout=120 # 120 seconds (2 minutes)
        elapsed=0
        until curl --output /dev/null --silent --head --fail http://localhost:8199; do
            if [ $elapsed -ge $timeout ]; then
                echo "Server did not become ready in time. Failing the workflow."
                exit 1
            fi
            printf '.'
            sleep 5
            elapsed=$(($elapsed + 5))
        done
        echo "Server is up and running!"
      
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
