name: Playwright Tests
on:
  push:
    branches: [ main, master, refactor/feed ]
  pull_request:
    branches: [ main, master, refactor/feed ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Docker compose environment
      run: docker-compose --env-file .env.ci -f docker-compose.ci.yml up -d

    - name: Wait for server and containers to be ready
      run: |
        echo "Waiting for server and containers to be ready..."
        timeout=180 # 180 seconds (3 minutes)
        elapsed=0
        until curl --output /dev/null --silent --head --fail http://localhost:8199; do
            if [ "$(docker-compose ps | grep 'Up' | wc -l)" -ne 2 ]; then
                echo "Number of 'Up' containers is not 2. Failing the workflow."
                docker logs accelasearch-module
                exit 1
            fi
            if [ $elapsed -ge $timeout ]; then
                echo "Server did not become ready in time. Failing the workflow."
                exit 1
            fi
            printf '.'
            sleep 5
            elapsed=$(($elapsed + 5))
        done
        echo "Server and containers are up and running!"

    - name: Disable backoffice TOKEN
      run: docker exec accelasearch-module bash -c "echo 'SetEnv _TOKEN_ disabled' >> /var/www/html/.htaccess"

    - name: Install composer dependencies
      run: docker exec accelasearch-module bash -c "cd /var/www/html/modules/accelasearch && composer install --no-dev --optimize-autoloader"

    - name: Install module
      run: docker exec accelasearch-module bash -c "cd /var/www/html && php bin/console prestashop:module install accelasearch"

    - name: Install dependencies
      run: npm ci
    - name: Build module
      env:
        CI: false
      run: |
        cd react
        npm ci
        npm run build
        cd ..
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
