name: Release and publish
on:
  release:
    types: [released, prereleased]

jobs:
  build:
    name: Build the base artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Install composer local modules
        run: composer dump-autoload -o --no-dev

      - name: Bump version
        run: make version
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}
          path: ./

  clean-artifacts:
    name: Clean previous artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GA_ACCESS_TOKEN }}
        with:
          version: "${{ steps.tagger.outputs.tag }}"
          name: "${{ steps.tagger.outputs.tag }}"

      - name: Clean existing assets
        shell: bash
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          assets=`bin/hub api -t repos/${{ github.repository }}/releases/${{ steps.release_info.outputs.id }}/assets | awk '/\].url/ { print $2 }'`
          for asset in $assets
          do
            bin/hub api -X DELETE $asset
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GA_ACCESS_TOKEN }}

  upload_release_asset_production:
    name: Upload the production zip asset to the release
    runs-on: ubuntu-latest
    needs: [build, clean-artifacts]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ github.event.repository.name }}

      - name: Bundle the production zip
        run: |
          cd ${{ github.event.repository.name }}
          echo "$CONFIG_FILE" >> .config.prod.yml
          make zip-me-prod

      - name: Publish the production zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GA_ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}/releases/accelasearch.zip
          asset_name: accelasearch.zip
          asset_content_type: application/zip
